### ISSUE TITLE
chase example, turnLightOn to turnOnLight

### ISSUE THREAD

**Issue by hirotakaster** [toio/toio.js#1]
Hi,

In example/chase/index.js sample, turnLightOn function is turnOnLight ? 

```
  jerry.turnLightOn
  tom.turnOnLight
```
to 
```
 jerry.turnOnLight
 tom.turnOnLight
```

thank you.

**Comment by TakeshiYaeda** [comment]
@hirotakaster Thank you for your feedback. You are right.
I will fix it soon.

**Comment by hirotakaster** [comment]
thx!!
