### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by d30tajima** [toio/toio.js#19]
toio.jsをgit cloneした後にyarn install, buildをすると下記のようなエラーが出てしまいます．
![image](https://user-images.githubusercontent.com/11310448/76587917-d2536780-6528-11ea-9291-d704fb373c37.png)

新規機能のMoveToに関連するコードでbuild errorになってしまいます．

toio.js\packages\cube\src\characteristics\specs\motor-spes.ts
"""
      // When coordinates are not defined, they are not changed.
      const x = target.x ?? 0xffff
      const y = target.y ?? 0xffff
"""

今一度、コードを確認していただいてもいいでしょうか？

yarnおよびnodejsのversionは下記のとおりです．
![image](https://user-images.githubusercontent.com/11310448/76587931-e26b4700-6528-11ea-9a75-39c14f433870.png)

**Comment by TakeshiYaeda** [comment]
@d30tajima 報告ありがとうございます．現在のmasterブランチは依存モジュールのtypescriptのバージョン不一致によりビルドに失敗する状態です．

v1.0.0をお使いいただくか， 現在のmasterに #10 (update-jestブランチ)を手元でマージしていただくとビルドできるようになります．#10 はテスト関連の実装完了の後にマージの予定です．

**Comment by d30tajima** [comment]
@TakeshiYaeda 確認ありがとうございます．
update-jestブランチをローカルでマージしたら無事buildされ、exampleも動きました，

対応ありがとうございます！

**Comment by TakeshiYaeda** [comment]
@d30tajima ご確認ありがとうございます！
