### ISSUE TITLE
XpcConnectionのbuildでエラー

### ISSUE THREAD

**Issue by akiporoyopida** [toio/toio.js#22]
node@8に下げてもだめでした。。
<img width="839" alt="スクリーンショット 2020-05-07 17 59 03" src="https://user-images.githubusercontent.com/1607194/81275755-111b1f00-908d-11ea-9498-711e00712440.png">

**Comment by TakeshiYaeda** [comment]
報告ありがとうございます．
これはどういったのコマンド出力結果でしょうか？

**Comment by akiporoyopida** [comment]
git clone https://github.com/toio/toio.js.git
cd toio.js
yarn install
です。

**Comment by TakeshiYaeda** [comment]
@akiporoyopida masterは開発中で一時的にビルドできない状態なので，tagバージョンをお使いいただくか， #19 を参考に変更いただくとビルドできるようになります．

**Comment by akiporoyopida** [comment]
ありがとうございます。
update-jest 
git clone https://github.com/toio/toio.js.git
cd toio.js
git merge origin/update-jest
yarn install（yarn upgrade）

tagバージョンも

**Comment by akiporoyopida** [comment]
git clone https://github.com/toio/toio.js.git -b replace-noble
repalce-nobleブランチはyarn install通りました。

**Comment by akiporoyopida** [comment]
git clone https://github.com/toio/toio.js.git
cd toio.js
yarn install
yarn build

yarn example:keyboard-control

iTerm2ではなく、ターミナルであれば
yarn installでエラーが出ますが、サンプル動作しました。。
https://developer.apple.com/forums/thread/675773
